# -*- coding: utf-8 -*-
"""Copy of huma bushra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SsWEFNkD_WziuKNvyDqEijQEFDboT2Et
"""

tuple=(tuple,set,dict,list)
type(tuple)

#List
type([1,2,3,4,5,7])

#Dictionary
{'Name':'bushra', 'Roll_no':22, 'age':23}

#to do
#make a dictionary add own data
dict={'Name':'bushra','College':'Bmsit', 'age':22, 'Course':'MCA'}
print(dict)

#Print function
print('Hello world')

#You have to print the type of the data and store it
str="Myself huma from BMSIT, pursuing my MCA in 4th sem..Doing my intership on data science in DLithe."
print(str)

#Variables and identifiers
str1='hello world Im huma'
str1

#Data operators
34*2

a=35
b=3
# Multiplication *
# Division /
# Floor division //
# Addition +
# Substraction -
# Exponention **

# addition
a + b

#division
a/b

#multiplication
a*b

#substraction
a-b

34==20

#Assignment opertors
x=12
x*=4
print(x)

#Assignment opertors
x=12
x*=3
print(x)

x+=2
print(x)

"""python logical operators

1.And
2.Or
3.Not
"""

# and 
23>45 and 49 == 49

#or
23>45 or 49 != 49 or 2 == 2

'Huma'=='huma'

#not operator
not('huma' == 'Huma')

"""04-03-2022 Task-2

What are sequences in python

They are the containers with items that are accessiblr by indexing or string

1.Concatenation 2.Repeatation 3.Membership testing 4.Slicing 5.Indexing
"""

#append
li = [1,4,8,3,9,5,2]
li.append(7)
print(li)

#insert
li = [4,7,8,9]
li.insert(5,9)
print(li)

#to do
#you have to insert 37 in 8th index and 2 in 12th index and 5 in 1000 index 

li = [1,3,4,5,6,7,8,9,10,11,23,67,89,23,12,78,90,22,67,88,89]
li.insert(8,37)
print(li)
li.insert(2,12)
print(li)
li.insert(100,5)
print(li)

#extend
ex1 = [1,2,3,4,5,6,7]
ex2 = [4,8,9,10,34]
ex1.extend(ex2)
ex2.extend(ex1)
print("Extended list after adding ex2",ex1)
print("Extended list after adding ex1",ex2)

#sum
print(sum(ex2))

#count
count1 = [1,4,6,87,36,86,90,65,2,2,2,2,2,37,86,36,89,62,91,63]
print(count1.count(2))

#indexing
In = [6,7,8,9,2,3,4,1]
In.index(3)

In[3]

In[3:7]

dc = [3,4,3.6,8,8,9,5,8,3,9,1,3,5,9]
min(dc)

#pop
pop1 =[1,2,3,4,5,6,7,8,9]
a = pop1.pop(4)
print(pop1)
print(a)

#max
max(dc)

pop1.pop()

delete = [2,3,4,5]
del delete[2]
delete

#remove
remove1 = [2.3,4,3,8,17]
b = remove1.remove(4)
print(remove1)

print(remove1)

#To do
#a = 12
#b = 3
#c = 45
#Write a swapping where a == c, b == a, c = b
a = 12
b = 3 
c = 45

a,c = c,a
print("after swapping")
print(a)

b,c= c,b
print("after swapping")
print(b)

c,a = a,c
print("after swapping")
print(a)

x = 23
y = 9
temp = x
print(temp)
x = y
y = temp
print(x)
print(y)

x,y = y,x
print(x)
print(y)

"""STRING"""

name = 'huma'
course = 'MCA'
name.capitalize()

name.count("a")

name.find("h")

name.isalpha()

name.islower()

name.lower()

name.upper()

name.strip()

a = "python is a programming language"
a.split(" ")

a.split("is")

b = "Python"
c = "Language"
b+c
b + " "+ b

a*3

str1 = 'Hello to the kingdom'
len(str1)

"""#05-03-2022 TASK 3

TUPLES
"""

this1 = ('mango','banana','orange','kiwi','melon','mango')

this1[1]

this1[3:5]

tuple1 = (1,2,3,4)
tuple2 = ('abc',3,4,'bnh')
tuple3 = tuple1 + tuple2
print(tuple3)

tu1 = ('hello','world')
print(tu1)

#tuple unpacking
tuple4 = ("hello",'good','people')
a,b,c = tuple4
print(a)
print(b)
print(c)

dic ={'name':'huma','age':23}
#deleting the key
del dic["name"]
print(dic)

dic ["number"] = 1234
dic ["name"] = "huma"
print(dic)

dic.pop("age")

print(dic)

"""Double-click (or enter) to edit

#if condition to execute(When the statement is true)
#if condition:
 # statement1
  #stat2
  #
#stat3

#else:
  #stat4
"""

i = 5
if (i<25):
  print("i is less than 25")

print('I am not in if block')

#To do 
#specify what it is doing : if the assigned value is equal to the initialized value the print hello or else print the initialized value thrice
#also mention and clear errors : indentation

string = "Huma"
if string == "Huma":
  print('hello')
else:
  string = string*3
  print(string)

string = "Huma"
if string == "Humaa":
  print('hello')
else:
  string = string*3
  print(string)

i = 20
if (i<15):
  print("i is smaller than 15")
  print("i am in if block")

else:
  print("i is greater or equal to 15")
  print("i am in else block")

#Nested if-else
i = 40
if (i == 40):
  if(i<=15):
    print("i is smaller than 15")

  if(i<12):
    print("i is smaller than 12 too")

  else:
    print('i is greater than 15')

else:
  print()